### PR TITLE
Please, Add 'Truly clean' style for once!!!

### PR DESCRIPTION
**Pull request by iEnderMan06**

### CODE REVIEW

**Comment by ZombiePwner1** [comment]
@Luke18033 @TeamSpen210 What is this style?

**Comment by iEnderMan06** [comment]
@ZombiePwner1 A custom one I made. "An updated, sleeker version of the Clean Style, as an alternative to Orignal Clean. Improvements include removal of randomised ceilings and a warmer tileset." https://imgur.com/a/KyvBQ

**Comment by ZombiePwner1** [comment]
@iEnderMan06 Ah alright aside from the ceiling change theres not much of a change.

**Comment by LautaroL20** [comment]
@iEnderMan06 - Is your Style still WIP, or it is finished?

**Comment by Luke18033** [comment]
Is this still in progress or can I close it?

**Comment by LautaroL20** [comment]
I think that our dude "IEnderMan06" is pretty much dead at the Beemod community right now. I guess we will have to take care ourselves from this style in case that there are still thing to do.

**Comment by LautaroL20** [comment]
However, id like to rename this style to something else, as well as modify the description though.

**Comment by Neightro** [comment]
How about "Brand New" for a title since that seems to be the premise of it—that it was freshly built by GLaDOS?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
This could be a style-var instead, i don't need the need to warrant a whole new style just to make the walls' a little cleaner.

**Comment by LautaroL20** [comment]
@BETTEREXTENEDEDITORMOD - Considering that there are two clean styles available in beemod that the only difference is that it changes the tiles, i do not see the point of why this would have to be an exception. Also, making this a stylevar would be pretty much inconsistent, people may do not see it.

**Comment by LautaroL20** [comment]
This pull request seems pretty much dead, what is the point of having it open? The author will never get back to this...

**Pull request closed without merging**
