### PR TITLE
Add more global settings for turrets

### PR DESCRIPTION
**Pull request by GiovanH**
For #3479 

Adds a "Super Damage" setting that toggles super damage mode for all turrets
Adds a "Shoot through portals" setting that controls whether or not turrets can shoot through portals

Also renames the "Fizzler" settings group (currently with a single laserfield setting) to "Hazards", and includes turrets in that grouping.

### CODE REVIEW

**Comment by TeamSpen210** [comment]
Note the fizzler group ID is currently hardcoded into the [fizzler logic](https://github.com/BEEmod/BEE2.4/blob/53e484c14cb77515af5b9c2fa81a05eb7b389726/src/fizzler.py#L383), it should probably be kept separate. Other stuff like portal bumping controls might be in that.

**Comment by GiovanH** [comment]
Ah, that's why I couldn't find reference to it. Will do.

**Comment by GiovanH** [comment]
> Note the fizzler group ID is currently hardcoded into the [fizzler logic](https://github.com/BEEmod/BEE2.4/blob/53e484c14cb77515af5b9c2fa81a05eb7b389726/src/fizzler.py#L383), it should probably be kept separate. Other stuff like portal bumping controls might be in that.

Latest version should tolerate the hardcoded string

**Comment by maxdevgithub** [comment]
> Adds a "Super Damage" setting that toggles super damage mode for all turrets
I believe it would be rather a damage slider

**Comment by GiovanH** [comment]
> > Adds a "Super Damage" setting that toggles super damage mode for all turrets
> > I believe it would be rather a damage slider

Valve does not implement super damage as a damage slider; "super damage" is a binary option.

**Pull request merged**
