### PR TITLE
Add Portal Pro music pack

### PR DESCRIPTION
**Pull request by Byzarru**
Includes the nine tracks from the mod, Portal Pro. Permissions still need to be granted by Mevious for use of these tracks.

### CODE REVIEW

**Comment by LautaroL20** [comment]
Well, it seems that Mevious hasn´t given permission for this.....

**Comment by TeamSpen210** [comment]
I asked, he's given permission.

**Comment by Byzarru** [comment]
Can this be merged then as soon as the icons are resized?

**Comment by TeamSpen210** [comment]
Yep.

**Pull request merged**
