### PR TITLE
Fix glass being portalable.

### PR DESCRIPTION
**Pull request by slambo312**
"Couldn't fix it"

### CODE REVIEW

**Comment by slambo312** [comment]
Good point.

**Comment by slambo312** [comment]
Fixing it right now.

**Comment by slambo311** [comment]
> Glass is actually hardcoded to always be non-portalable.

#3966

**Comment by slambo311** [comment]
Alright, I'll try and fix it. I'm still in school and don't have access to my Windows PC right now, so it'll be a little more difficult. I'll try to do it on my Chromebook and then put it onto my "organization" that has both of my accounts, so I can do it on Windows after school.

**Comment by Luke18033** [comment]
Yeah you don't actually know how any of this works, just let one of us handle this.

**Comment by slambo312** [comment]
Yeah, good point.

**Pull request closed without merging**
