### PR TITLE
Pre - Release 24

### PR DESCRIPTION
**Pull request by TeamSpen210**
* New Items:
    * Cube coloriser, for marking cubes to allow distinguishing between them.
    * Static Half Panels
    * Cold Light Strips
    * Protruding Pedestal Button
    * Connection Signage item variant
    * Cube Cleaners
    * Angled Block Corners

* Larger icons for music and elevator videos
* Fully support Coop in Aperture Tag in all Styles.
* In Coop, BEE triggers can be set to only activate when both players are inside.
* Add additional mode to Tag fizzlers which turns off one colour.
* Improved appearance of P1 cube and weighted buttons (fixing several bugs).
* Reduce size of P1 cubes to match P2 cubes.
* Add new editor models for Old Aperture fizzlers (based on August's TAG fizzler models).
* Improve design of BTS buttons.
* Fix some bugs with BEE Pellet emitter and catcher editor models.
* Increase number of holes in Clean Cutout Tiles.
* Add 50s style shape signage (this removes the random markings used).
* Random missing tiles for Overgrown buttons.
* Add glow to Excursion Funnels.
* Make Rexaura Cube Deflectors handle not having the 'Pellets Fizzle Cubes' stylevar enabled.

### CODE REVIEW

**Comment by ZombiePwner1** [comment]
Well this will be intresting :D

**Comment by Byzarru** [comment]
What of the TDB fizzlers?

**Comment by TeamSpen210** [comment]
They currently don't have styled versions, so they're not done.

**Comment by TheDarkBomber** [comment]
So, PR24.1????

**Comment by Luke18033** [comment]
@TheDarkBomber - Pr24 technically hasn't been released yet.

**Comment by TheDarkBomber** [comment]
Somebody add the styled variants!

**Comment by Luke18033** [comment]
@TheDarkBomber - You add them on your repo, and @TeamSpen210 will merge it!

**Comment by Luke18033** [comment]
Or I could, but I'd want to get @TeamSpen210's permission first...

**Comment by Byzarru** [comment]
> TeamSpen210 @TeamSpen210 18:29
> Commit on your fork and I'll merge it in.

**Comment by TheDarkBomber** [comment]
I don't know how to add P1 variants.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Please sync your app before uploading packages, i added a missing texture on model.

**Comment by LautaroL20** [comment]
I hope its not too late...............

**Comment by TeamSpen210** [comment]
I've still got to make the protruding Overgrown version and some other things.

**Comment by TheDarkBomber** [comment]
You forgot my fizzlers. 😒

**Comment by ZombiePwner1** [comment]
Hahahaha r.i.p @TheDarkBomber

**Comment by TheDarkBomber** [comment]
RIP @ZombiePwner1.

**Comment by LautaroL20** [comment]
No, this (https://github.com/BEEmod/BEE2-items/pull/1421/commits/6404e08c7be8c4f4bf5a04af1bcd0621b7b84d6f) wasn´t really a duplicate material....... 
Yours had differents parameters and also was into a different folder. Your commit caused my Protruding Editor Models to have a missing frame on its base......

**Comment by TheDarkBomber** [comment]
Then there would have to be a PR24.1.

**Comment by TheDarkBomber** [comment]
@Luke18033 Yes, the `dev` branch should be deleted! Not.

**Comment by Luke18033** [comment]
No, I was referring to the `gridded_wall` branch.

**Pull request merged**
