### PR TITLE
Does not spit fire :(

### PR DESCRIPTION
**Pull request by Blacksilver42**
Changed Crusher's description.

### CODE REVIEW

**Comment by TeamSpen210** [comment]
Ok, why not :)

**Comment by Luke18033** [comment]
Why did you merge this? It's completely nonsensical, nobody is going to expect crushers to spit fire (although they do in 60s).

**Comment by TeamSpen210** [comment]
Wheatley was wanting to add that feature.

**Comment by Luke18033** [comment]
Huh, okay. I still don't think it really needs to be there, but no specific reason to get rid of it for now.

**Pull request merged**
